create table if not exists grupos (
    id          bigint generated by default as identity primary key,
    nome        text not null unique,
    localizacao text,
    criado_em   timestamptz default now()
);

create table if not exists pessoas (
    id       bigint generated by default as identity primary key,
    grupo_id bigint not null references grupos (id) on delete cascade,
    nome     text not null,
    idade    integer not null
);

create table if not exists suprimentos (
    id                    bigint generated by default as identity primary key,
    grupo_id              bigint not null references grupos (id) on delete cascade,
    nome                  text not null,
    quantidade_atual      numeric not null,
    consumo_diario_padrao numeric not null,
    unidade_medida        text not null,
    categoria             text not null default 'outro',
    validade              date
);