create table if not exists historico (
    id          bigint generated by default as identity primary key,
    grupo_id    bigint not null references grupos (id) on delete cascade,
    suprimento  text not null,
    quantidade  numeric not null,
    tipo        text not null default 'atualizacao',
    criado_em   timestamptz default now()
);

create index if not exists idx_historico_grupo on historico (grupo_id, criado_em);